name: product_finder
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Auth buttons
  auth_buttons: ^3.0.0
  # State management packages
  provider:
  flutter_bloc:
  equatable:
  flutter_shimmer:
  # Firebase and auth packages
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0
  flutterfire_ui: ^0.4.3+20
  google_sign_in:
  # product finder
  flutter_barcode_scanner:
  speech_to_text: ^6.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/product.json
    - assets/images/
