name: product_finder
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner:
  speech_to_text: ^6.1.1
  flutter_bloc:
  url_launcher: ^6.1.10
  equatable:
  font_awesome_flutter:
  # Firebase and auth packages
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0
  flutterfire_ui:
  firebase_auth:
  firebase_auth_web:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.jpg
    - assets/product.json
    - assets/images/image.png
